import "server-only";
/**
 * Document files on disk.
 *
 * Copyright (C) 2026 StoneDogCode L.L.C.
 * SPDX-License-Identifier: AGPL-3.0-only
 *
 * Files live on the mounted volume beside the database, not inside it. A blob
 * column would bloat the SQLite file, slow every unrelated query, and break the
 * backup story this tier promises — "copy /data somewhere" has to remain true.
 */

import { mkdir, readFile, unlink, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { randomUUID } from "node:crypto";
import { renamedEnv } from "./upgrade";

const DOCUMENTS_DIR =
  renamedEnv("DOCUMENTS_DIR") ??
  join(renamedEnv("DB_PATH")?.replace(/\/[^/]+$/, "") ?? "/data", "documents");

/**
 * The upload ceiling.
 *
 * Generous enough for a scanned multi-page determination letter, small enough
 * that a single request cannot fill a self-hoster's volume. Enforced on the
 * server rather than trusted from the client.
 */
export const MAX_UPLOAD_BYTES = 25 * 1024 * 1024;

/**
 * What may be uploaded.
 *
 * An allowlist, not a blocklist. **`image/svg+xml` and `text/html` are absent
 * deliberately** — both can carry script, and a browser rendering one from this
 * origin would be executing attacker-supplied code with the user's session.
 * They are also the two formats people most plausibly want, which is exactly
 * why the omission needs to be written down rather than looking like oversight.
 */
export const ALLOWED_CONTENT_TYPES: Readonly<Record<string, string>> = {
  "application/pdf": "pdf",
  "image/png": "png",
  "image/jpeg": "jpg",
  "image/webp": "webp",
  "image/tiff": "tiff",
  "text/plain": "txt",
  "application/msword": "doc",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document": "docx",
};

/**
 * A fresh, opaque storage key.
 *
 * **The user's filename never reaches the filesystem.** It is kept in the
 * database for display only. A name like `../../../data/optima.sqlite` reaching
 * a path join is how an upload form becomes an arbitrary-write primitive, and
 * sanitising such a name correctly is far harder than not using it at all.
 */
export function newStorageKey(contentType: string): string {
  const extension = ALLOWED_CONTENT_TYPES[contentType] ?? "bin";
  return `${randomUUID()}.${extension}`;
}

function pathFor(storageKey: string): string {
  // Belt and braces. The key is generated by us and cannot contain a separator,
  // but this function is one refactor away from being handed something else.
  if (storageKey.includes("/") || storageKey.includes("\\") || storageKey.includes("..")) {
    throw new Error(`Refusing to build a path from ${JSON.stringify(storageKey)}`);
  }
  return join(DOCUMENTS_DIR, storageKey);
}

export async function saveFile(storageKey: string, bytes: Uint8Array): Promise<void> {
  await mkdir(DOCUMENTS_DIR, { recursive: true });
  await writeFile(pathFor(storageKey), bytes);
}

export async function readStoredFile(storageKey: string): Promise<Buffer> {
  return readFile(pathFor(storageKey));
}

export async function deleteStoredFile(storageKey: string): Promise<void> {
  // A missing file is not an error here: the row is the record of truth, and
  // refusing to delete it because the blob already vanished would strand it.
  await unlink(pathFor(storageKey)).catch(() => undefined);
}

export interface UploadCheck {
  ok: boolean;
  error?: string;
}

export function checkUpload(file: File): UploadCheck {
  if (file.size === 0) return { ok: false, error: "That file is empty." };
  if (file.size > MAX_UPLOAD_BYTES) {
    return {
      ok: false,
      error: `That file is ${(file.size / 1024 / 1024).toFixed(1)} MB. The limit is ${MAX_UPLOAD_BYTES / 1024 / 1024} MB.`,
    };
  }
  if (!(file.type in ALLOWED_CONTENT_TYPES)) {
    return {
      ok: false,
      error: `${file.type || "That file type"} is not accepted. Upload a PDF, image, plain text, or Word document.`,
    };
  }
  return { ok: true };
}
